version: '3'

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: jadersonbrandao/nginx-desafio:prod
    container_name: nginx-desafio
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: jadersonbrandao/app-desafio:prod
    container_name: app-desafio
    # entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db    

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0  --init-file ./mysql/data/init.sql
    container_name: db
    tty: true
    volumes:
      - .docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network    
  
networks:
  node-network:
    driver: bridge